title: hackherway
description: Cybersecurity, Active Directory, and offensive research
url: https://d0midigi.github.io
baseurl: "/hackherway"

markdown: kramdown
highlighter: rouge


plugins:
  - jekyll-feed
